




ESP32  SETUP

.............................................................................................
---------------------------------------------------------------------------------------------


captive_portal:

external_components:
  - source:
      type: local
      path: mycomp
    components: [sen21231]

  # Example configuration entry for ESP32


#external_components:
#  - source:
#      type: git
#      url: https://github.com/shreyaskarnik/esphome-components
#    components: [sen21231]
    
i2c:
  sda: GPIO04
  scl: GPIO05
  scan: true
  id: bus_a

sensor:
  - platform: sen21231
    presence_detected:
        name: "Number of persons detected"
    presence_box_confidence:
        name: "Is person in box confidence"
    presence_box_left:
        name: "Pixel from left to persons box"
    presence_box_top:
        name: "Pixel from top to persons box"
    presence_box_right:
        name: "Pixel from right to persons box"
    presence_box_bottom:
        name: "Pixel from bottom to persons box"
    presence_id_confidence:
        name: "Is persons ID confidence"
    presence_id:
        name: "Persons matching ID detected"
    facing_camera:
        name: "Person is facing camera"
